### ISSUE TITLE
Deploy 3_0_3 on Jahia Store

### ISSUE THREAD

**Issue by marob** [Jahia/Social-module#1]
Latest Workspace Factory (3.1.1) requires the latest Jahia Social Module (3.0.3), in particular the org.jahia.modules.sociallib.OsgiActivityRecorderService class.

But Jahia Social Module 3.0.3 is not available on Jahia Store (except via "Workspace Factory - Enterprise Distribution" embedded modules).

Generally speaking, shouldn't every released module be available on Jahia Store?

**Comment by rknj** [comment]
Jahia Social Module 3.0.3 is now available on store.jahia.com. Thanks for the notification. Indeed, all the released modules should be availabe on our store but an oversight can happen, so don't hesitate to notify us if you notice this again !
